In [1]:
#1. Write a Python Program to Add Two Matrices?
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [2]:
#2. Write a Python Program to Multiply Two Matrices?
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [3]:
#3. Write a Python Program to Transpose a Matrix?
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
a = ['b','c','a','t']
a.sort()
a

['a', 'b', 'c', 't']

In [7]:
#5. Write a Python Program to Remove Punctuation From a String?
a = 'rahul.;!l'
punc = '''!()-[]{};:'"\, <>./?@#$%^&*_~'''
for i in a:
    if i in punc:
        a = a.replace(i,'')
a

'rahull'